import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const require = createRequire(import.meta.url);
const {
  isReservedName,
  sanitizeAssetName,
  sanitizeFolder,
  latexFileAccessViolation,
  isLoopback,
  safeProjectWriteSync,
  writeDocumentBundleSync,
  catastrophicTexShrink,
} = require('../server.js');

test('Windows予約名と危険なasset名を拒否する', () => {
  for (const name of ['CON', 'nul.txt', 'COM9.log', 'name.', 'name ']) {
    assert.equal(isReservedName(name), true, name);
  }
  for (const name of ['../x.png', '.hidden', 'a/b.png', 'a\\b.png', 'a..png', 'NUL.txt']) {
    assert.equal(sanitizeAssetName(name), null, name);
  }
  assert.equal(sanitizeAssetName('figure-1.png'), 'figure-1.png');
});

test('論理フォルダを正規化し、脱出・隠し・過深階層を拒否する', () => {
  assert.equal(sanitizeFolder(' papers\\2026 '), 'papers/2026');
  for (const folder of ['../x', '/x', 'x//y', '.git', 'a/b/c/d/e/f/g/h/i', 'AUX/docs']) {
    assert.equal(sanitizeFolder(folder), null, folder);
  }
});

test('LaTeXの絶対パス・親ディレクトリ参照を拒否する', () => {
  for (const latex of [
    String.raw`\input{/etc/passwd}`,
    String.raw`\includegraphics{../secret.png}`,
    String.raw`\input C:\\secret.tex`,
    String.raw`\openout1=../../escape.txt`,
  ]) assert.equal(latexFileAccessViolation(latex), true, latex);

  assert.equal(latexFileAccessViolation(String.raw`\includegraphics{figures/a.png}`), false);
  assert.equal(latexFileAccessViolation(String.raw`\bibliography{refs}`), false);
});

test('loopback表記だけをローカル接続として扱う', () => {
  for (const address of ['127.0.0.1', '127.12.3.4', '::1', '::ffff:127.0.0.1']) {
    assert.equal(isLoopback({ socket: { remoteAddress: address } }), true, address);
  }
  for (const address of ['192.168.1.2', '10.0.0.3', '::ffff:192.168.1.2', '']) {
    assert.equal(isLoopback({ socket: { remoteAddress: address } }), false, address);
  }
});

test('main.tex 上書き前に自動バックアップを残す', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ratex-backup-'));
  try {
    const original = Buffer.from('\\documentclass{acmart}\nORIGINAL PAPER\n');
    fs.writeFileSync(path.join(dir, 'main.tex'), original);
    safeProjectWriteSync(dir, 'main.tex', Buffer.from('% Generated\nNEW\n'));
    const recovery = path.join(dir, '.ratex-recovery', 'main.tex');
    const backups = fs.readdirSync(recovery);
    assert.equal(backups.length, 1);
    assert.deepEqual(fs.readFileSync(path.join(recovery, backups[0])), original);
    assert.equal(fs.readFileSync(path.join(dir, 'main.tex'), 'utf8'), '% Generated\nNEW\n');
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('大きな main.tex を空に近い内容で上書きする要求を拒否する', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ratex-loss-'));
  try {
    const original = Buffer.from('\\documentclass{acmart}\n' + '論文本文'.repeat(1000));
    const emptyGenerated = Buffer.from('% Generated by TailorTeX\n\\begin{document}\n\\end{document}\n');
    fs.writeFileSync(path.join(dir, 'main.tex'), original);
    assert.equal(catastrophicTexShrink(original, emptyGenerated), true);
    assert.throws(
      () => safeProjectWriteSync(dir, 'main.tex', emptyGenerated),
      (error) => error && error.code === 'CONTENT_LOSS_BLOCKED'
    );
    assert.deepEqual(fs.readFileSync(path.join(dir, 'main.tex')), original);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('文書一括保存が途中失敗したら元ファイルへロールバックする', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ratex-bundle-'));
  try {
    fs.writeFileSync(path.join(dir, 'main.html'), '<p>ORIGINAL</p>');
    fs.writeFileSync(path.join(dir, 'main.tex'), 'ORIGINAL TEX');
    // refs.bib をディレクトリにして3件目の書き込みを意図的に失敗させる。
    fs.mkdirSync(path.join(dir, 'refs.bib'));
    assert.throws(() => writeDocumentBundleSync(dir, {
      'main.html': '<p>NEW</p>', 'main.tex': 'NEW TEX', 'refs.bib': 'NEW BIB',
    }));
    assert.equal(fs.readFileSync(path.join(dir, 'main.html'), 'utf8'), '<p>ORIGINAL</p>');
    assert.equal(fs.readFileSync(path.join(dir, 'main.tex'), 'utf8'), 'ORIGINAL TEX');
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});
